# menggunakan docker compose versi 3.8 (latest)
version: "3.8"
# definisikan service apa saja yang akan digunakan
services:
# service item app
  item-app:
  # pull image dari github packages container registry
    image: ghcr.io/maplezs/item-app:v1
    # memetakan port 80 di host ke port 8080 di container
    ports:
      - "80:8080"
    # service item-app hanya akan berjalan setelah item-db sudah berjalan
    depends_on:
      - item-db
    # docker akan selalu memulai ulang kontainer jika berhenti
    restart: always
# service item app
  item-db:
   # menggunakan image mongo versi 3 dari docker hub
    image: mongo:3
    # docker akan selalu memulai ulang kontainer jika berhenti
    restart: always
    # memetakan volume ke direktori container
    volumes: ["app-db:/data/db"]
# mendefinisikan volume
volumes:
  app-db: