version: 2.1
jobs:
# jobs untuk lint Dockerfile
  lint-dockerfile:
  # menggunakan docker execution environment
    docker:
    # image base dari circleci base image ubuntu yang dapat menjalankan docker
    - image: cimg/base:current
    steps:
    # checkout source code
    - checkout
    # menjalankan docker command pada remote environment CircleCI
    - setup_remote_docker
     # melakukan lint Dockerfile dengan menggunakan docker image hadolint
    - run:
        name: Lint Dockerfile menggunakan hadolint
        command: |
          docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

# jobs untuk menjalankan unit test
  test-app:
  # menggunakan docker execution environment
    docker:
    - image: cimg/go:1.15.15
    steps:
    # checkout source code
    - checkout
    # menjalankan docker command pada remote environment CircleCI
    - setup_remote_docker
    - run:
        name: menjalankan unit test untuk aplikasi backend
        command: |
          go test -v -short --count=1 $(go list ./...)

# jobs untuk build dan push image
  build-app-karsajobs:
  # menggunakan docker execution environment
    docker:
    - image: cimg/base:current
    steps:
    # checkout source code
    - checkout
    # menjalankan docker command pada remote environment CircleCI
    - setup_remote_docker
    - run:
        name: build lalu push image ke Github Packages Container Registry
        # tambah permission execute pada file sebelum eksekusi file
        command: |
          chmod +x build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh
  
workflows:
# nama workflow
  karsajobs-ci:
  # urutan eksekusi jobs
    jobs:
    - lint-dockerfile
    - test-app
    - build-app-karsajobs
